apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cicd-acme
spec:
  encryptedData:
    token: AgAFJE8aNxTA8KbQcMutAS3kjOMfmnY2i4lV4055ZBXtulSp/7RnqIY74ysiUgtnqLbOaCEOCjelpKe86ihWk+PJ30MwwYj2ZT0ciithRVhiJpz9WIY5L241txjilWPSV028nrQF2y3+1yusYQfTwN/y+Y3qHRuLz0sjMpKjxFeN3i3bGIoGDo2/vrua/2Z8IP+PuBtvxDojFj0TdrBU8h4n7LYXDth1a3bcpSoeZTLDlUveZol3aLtgzgqd7c8UxRXgGjk9XGcQ4htkOidKtcr2l30/F1LHEv8CH/xThVrKhd+bXX+Pu3P9H64sE3xt/5fWH/QJ6+KleGVrJsVhVO7VnxItfcCpAX9q7cKyBT31BSTDD/i52X3hXVy/O1KZkQ/Qj8J1C1OmRakDtYKYGjIR0Dv0QNQkFGk7PdkIAdJS+Y5NQan4zAI4vYc8QftPuibMH4Hj4/y+Sji1LcfvxPFyJmuH1HLa+Zb6qYIZo0F32SChgTqGO4jh+xPbZq7iUsOWqbm/4b3SqA0bDkxYbPNcDTiMVN+c6Z8qG3kExcn8kIdv/2jMu/AdJ/cBkgDUpmqvpIyuDiMw5PxFXnuD921dzJ6cHlKN9h1VGa6ptoms5sF7uljtxhPb5eQyI/rNO+z+hFIDSyLp6fbqpA00jP0mVdH8BP8X7P8mRGMmv2zRvS8MfBDK67+GR4IgloAa2ICJvNlfCebsdLLoxXJ4TtheTWgM4xeupojHRxPWYGq7+nw8U8CYQATu
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: cicd-acme

